#!/usr/bin/env node
/** Project the reviewed derived fixture into the source-only generated proof module. */

import { readFile, rename, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const PREFIX = [
    [1, 90],
    [0, 218],
    [1, 21],
    [0, 94],
    [2, 12],
    [5, 6],
    [3, 41],
    [0, 119],
    [2, 23],
    [0, 180],
    [1, 129],
    [0, 120],
    [2, 34],
];

function parseArguments(args) {
    if (args.length !== 4 || args[0] !== "--fixture" || args[2] !== "--output") {
        throw new TypeError("Usage: project_lander_route_proofs.mjs --fixture PATH --output PATH");
    }
    if (resolve(args[1]) === resolve(args[3])) throw new TypeError("Fixture and output paths must differ");
    return { fixture: args[1], output: args[3] };
}

function expanded(runs) {
    return runs.flatMap(([command, count]) => Array.from({ length: count }, () => command));
}

function compactRecord(record) {
    const commands = expanded(record.runs);
    const prefix = expanded(PREFIX);
    if (!prefix.every((command, index) => commands[index] === command)) {
        throw new Error(`Route ${record.pairKey} does not begin with the canonical prefix`);
    }
    const remainder = commands.slice(prefix.length);
    const macroCount = Math.floor(remainder.length / 12);
    const path = Array.from({ length: macroCount }, (_, index) => {
        const chunk = remainder.slice(index * 12, index * 12 + 12);
        if (!chunk.every((command) => command === chunk[0])) {
            throw new Error(`Route ${record.pairKey} has a nonuniform macro at ${index}`);
        }
        return chunk[0];
    }).join("");
    const tail = remainder.slice(macroCount * 12);
    if (tail.length > 0 && !tail.every((command) => command === tail[0])) {
        throw new Error(`Route ${record.pairKey} has a nonuniform tail`);
    }
    return [
        record.pairKey,
        path,
        tail[0] ?? 0,
        tail.length,
        record.scheduleDigest,
        record.success.contactStep,
        record.success.pose.x,
        record.success.pose.y,
        record.success.pose.vx,
        record.success.pose.vy,
        record.success.pose.angle,
        record.success.pose.angularVelocity,
        record.controllerBurn,
        record.baseBurn,
        record.climbSurcharge,
        record.allowance,
        record.maxHullTop,
        record.assignmentMembershipDigest,
        record.envelope,
        record.search.selectedLayer,
        record.search.macroExpansions,
        record.search.terminalReplays,
    ];
}

function render(fixture) {
    if (fixture.schema !== "agw-lander-route-derived/v9" || fixture.records?.length !== 312) {
        throw new Error("Expected the complete reviewed derived-v9 fixture");
    }
    const rows = fixture.records.map(compactRecord).map((row) => JSON.stringify(row));
    const rowLines = Array.from({ length: Math.ceil(rows.length / 4) }, (_, index) =>
        rows.slice(index * 4, index * 4 + 4).join(","),
    );
    const digests = {
        assignmentDigest: fixture.assignmentDigest,
        bootstrapDigest: fixture.bootstrapDigest,
        geometryDigest: fixture.geometryDigest,
        outputDigest: fixture.outputDigest,
        physicsDigest: fixture.physicsDigest,
        predecessorGeometryDigest: fixture.predecessorGeometryDigest,
        proofDigest: fixture.proofDigest,
        worldDigest: fixture.worldDigest,
    };
    return (
        `// @generated by website/tools/project_lander_route_proofs.mjs; do not edit.\n` +
        `const GENERATED_ROUTE_ROWS = Object.freeze([\n${rowLines.join(",\n")}\n]);\n` +
        `const GENERATED_ROUTE_PREFIX = Object.freeze(${JSON.stringify(PREFIX)}.map(Object.freeze));\n` +
        `function freezeGenerated(value) {\n` +
        `    if (Array.isArray(value)) value.forEach(freezeGenerated);\n` +
        `    else if (value && typeof value === "object") Object.values(value).forEach(freezeGenerated);\n` +
        `    return Object.freeze(value);\n` +
        `}\n` +
        `function decodeGeneratedRuns(path, tailCommand, tailCount) {\n` +
        `    const runs = GENERATED_ROUTE_PREFIX.map((run) => [...run]);\n` +
        `    const merge = (command, count) => {\n` +
        `        if (count === 0) return;\n` +
        `        if (runs.at(-1)[0] === command) runs.at(-1)[1] += count;\n` +
        `        else runs.push([command, count]);\n` +
        `    };\n` +
        `    for (const command of path) merge(Number(command), 12);\n` +
        `    merge(tailCommand, tailCount);\n` +
        `    return runs;\n` +
        `}\n` +
        `function generatedProof(row) {\n` +
        `    const [pairKey,path,tailCommand,tailCount,scheduleDigest,contactStep,x,y,vx,vy,angle,angularVelocity,controllerBurn,baseBurn,climbSurcharge,allowance,maxHullTop,assignmentMembershipDigest,envelope,selectedLayer,macroExpansions,terminalReplays] = row;\n` +
        `    return freezeGenerated({pairKey,envelope,assignmentMembershipDigest,runs:decodeGeneratedRuns(path,tailCommand,tailCount),scheduleDigest,search:{selectedLayer,macroExpansions,terminalReplays},success:{classification:"safe",contactStep,pose:{x,y,vx,vy,angle,angularVelocity}},controllerBurn,baseBurn,climbSurcharge,allowance,maxHullTop});\n` +
        `}\n` +
        `export const ROUTE_DIGESTS = Object.freeze(${JSON.stringify(digests)});\n` +
        `export const REFERENCE_PROOFS = freezeGenerated(GENERATED_ROUTE_ROWS.map(generatedProof));\n` +
        `export const REFERENCE_PROOF_CATALOG = freezeGenerated(Object.fromEntries(REFERENCE_PROOFS.map((proof) => [proof.pairKey, proof])));\n`
    );
}

async function main() {
    const { fixture, output } = parseArguments(process.argv.slice(2));
    const source = render(JSON.parse(await readFile(fixture, "utf8")));
    const temporary = `${output}.tmp-${process.pid}`;
    await writeFile(temporary, source, "utf8");
    await rename(temporary, output);
}

main().catch((error) => {
    console.error(error.stack ?? error.message);
    process.exitCode = 1;
});
