"""tmux session management for tasks.

Each task gets a locked-down tmux session. The session name follows the
pattern <workspace>--<task>. A restricted tmux config disables all interactive
session management (no splits, no new windows, no prefix key) while keeping
a large scrollback buffer.
"""

from __future__ import annotations

import shlex
from typing import Protocol

TASK_SEPARATOR = "--"
RESTRICTED_CONFIG_PATH = "/opt/agentworks/tmux-task.conf"
DEFAULT_HISTORY_LIMIT = 50_000

# Agent tmux socket infrastructure
AGENT_SOCKET_ROOT = "/run/agentworks/agent-tmux-sockets"
AGENT_SOCKET_GROUP = "tmux-agent-access"


class RunCommand(Protocol):
    """Callable that runs a shell command on a target (e.g. partial of ssh.run)."""

    def __call__(self, command: str, *, check: bool = True) -> object: ...


def derive_session_name(workspace_name: str, task_name: str) -> str:
    """Return the tmux session name for a task: <workspace>--<task>."""
    return f"{workspace_name}{TASK_SEPARATOR}{task_name}"


def agent_socket_path(linux_user: str, workspace_name: str, task_name: str) -> str:
    """Return the tmux socket path for an agent-mode task."""
    session = derive_session_name(workspace_name, task_name)
    return f"{AGENT_SOCKET_ROOT}/{linux_user}/{session}.sock"


def ensure_agent_socket_root(run_command: RunCommand, admin_username: str) -> None:
    """Create the agent tmux socket root directory and group (idempotent)."""
    grp = shlex.quote(AGENT_SOCKET_GROUP)
    admin = shlex.quote(admin_username)
    run_command(
        f"{{ getent group {grp} >/dev/null 2>&1 || /usr/sbin/groupadd {grp}; }} && "
        f"usermod -aG {grp} {admin} && "
        f"mkdir -p {AGENT_SOCKET_ROOT} && "
        f"chown root:{grp} {AGENT_SOCKET_ROOT} && "
        f"chmod 2770 {AGENT_SOCKET_ROOT}",
    )


def ensure_agent_socket_dir(run_command: RunCommand, linux_user: str) -> None:
    """Create a per-agent tmux socket directory (idempotent)."""
    q_user = shlex.quote(linux_user)
    grp = shlex.quote(AGENT_SOCKET_GROUP)
    q_path = shlex.quote(f"{AGENT_SOCKET_ROOT}/{linux_user}")
    run_command(
        f"mkdir -p {q_path} && "
        f"chown {q_user}:{grp} {q_path} && "
        f"chmod 2770 {q_path}",
    )


def build_socket_paths(
    tasks: list[object],
    get_agent_linux_user: object,
) -> dict[str, str | None]:
    """Build a session-name to socket-path map for a list of tasks.

    *get_agent_linux_user* is a callable ``(agent_name: str) -> str | None``
    that resolves an agent name to its Linux username (typically via DB lookup).
    """
    paths: dict[str, str | None] = {}
    for task in tasks:
        agent_name = getattr(task, "agent_name", None)
        ws = getattr(task, "workspace_name", "")
        name = getattr(task, "name", "")
        key = derive_session_name(ws, name)
        if agent_name:
            linux_user = get_agent_linux_user(agent_name)  # type: ignore[operator]
            paths[key] = agent_socket_path(linux_user, ws, name) if linux_user else None
        else:
            paths[key] = None
    return paths


def generate_restricted_config(history_limit: int = DEFAULT_HISTORY_LIMIT) -> str:
    """Generate the locked-down tmux config for task sessions.

    Loads the user's tmux.conf first so that familiar keybindings (prefix key,
    detach, copy mode, etc.) work for direct task attach. Then disables
    window/pane/session management on top to enforce one-task-per-session.
    When inside the console, the console's prefix eclipses the task's, so the
    task-level bindings are effectively invisible.
    """
    return f"""\
# Generated by agentworks. Do not edit.
# Locked-down config for task tmux sessions.
#
# Loads user tmux.conf for familiar keybindings (prefix, detach, copy mode),
# then disables window/pane/session creation to enforce one task per session.

# Load user config first
if-shell "test -f ~/.tmux.conf" "source-file ~/.tmux.conf"

# Large scrollback buffer (override user config)
set -g history-limit {history_limit}

# Size windows based on the most recently active client, not the smallest.
# Task sessions are created detached (default geometry) then attached from
# within the console session. Without this, the inner session stays stuck
# at the small detached size.
set -g window-size latest
set -g aggressive-resize on

# Disable status bar -- the console provides this when nested;
# for direct attach, the task is the only thing on screen.
set -g status off

# Disable window/pane/session creation and management.
# The user's prefix key, detach, copy mode, and scroll bindings are preserved.
unbind c          # new-window
unbind %          # split-window -h
unbind '"'        # split-window -v
unbind &          # kill-window
unbind x          # kill-pane
unbind n          # next-window
unbind p          # previous-window
unbind w          # choose-window
unbind s          # choose-session
unbind $          # rename-session
unbind ,          # rename-window
unbind .          # move-window
unbind !          # break-pane
unbind :          # command-prompt (prevents arbitrary tmux commands)
"""


def deploy_restricted_config(
    run_command: RunCommand,
    history_limit: int = DEFAULT_HISTORY_LIMIT,
) -> None:
    """Write the restricted tmux config to the VM."""
    config = generate_restricted_config(history_limit)
    # Ensure directory exists and write config
    run_command(f"sudo mkdir -p $(dirname {RESTRICTED_CONFIG_PATH})")
    run_command(f"sudo tee {RESTRICTED_CONFIG_PATH} > /dev/null << 'TMUX_CONF'\n{config}TMUX_CONF")


def tmux_cmd(base: str, socket_path: str | None = None) -> str:
    """Prepend ``-S <socket>`` to a tmux subcommand when a socket is given."""
    if socket_path:
        return f"tmux -S {shlex.quote(socket_path)} {base}"
    return f"tmux {base}"


def _grant_server_access(
    run_command: RunCommand,
    linux_user: str,
    socket_path: str,
) -> None:
    """Grant tmux server-access to every member of the socket group."""
    q_user = shlex.quote(linux_user)
    q_sock = shlex.quote(socket_path)
    grp = shlex.quote(AGENT_SOCKET_GROUP)
    run_command(
        f"for u in $(getent group {grp} | cut -d: -f4 | tr ',' ' '); do "
        f"sudo -u {q_user} tmux -S {q_sock} server-access -a \"$u\"; "
        f"done",
    )


def create_task_session(
    workspace_name: str,
    task_name: str,
    workspace_path: str,
    command: str,
    linux_user: str | None,
    *,
    run_command: RunCommand,
    is_admin: bool = True,
) -> None:
    """Create a locked-down tmux session for a task.

    For admin mode, the command runs directly on the admin's default tmux
    server.  For agent mode, the session is created as the agent Linux user
    with a per-task socket so the agent's tmux server (and shell) run under
    the agent's uid.  The admin gains access via group permissions on the
    socket and the tmux ``server-access`` ACL.
    """
    session = derive_session_name(workspace_name, task_name)
    q_session = shlex.quote(session)
    q_path = shlex.quote(workspace_path)

    if is_admin:
        if command:
            inner = shlex.quote(f"cd {q_path} && {command}")
            shell_cmd = f"$SHELL -lic {inner}"
        else:
            shell_cmd = ""

        cmd = f"tmux new-session -d -s {q_session} -c {q_path} -f {RESTRICTED_CONFIG_PATH}"
        if shell_cmd:
            cmd += f" {shlex.quote(shell_cmd)}"
        run_command(cmd)
    else:
        assert linux_user is not None
        q_user = shlex.quote(linux_user)
        sock = agent_socket_path(linux_user, workspace_name, task_name)
        q_sock = shlex.quote(sock)

        # Build the pane command.  sudo --login gives the agent a proper
        # login environment; tmux then starts the pane shell as that user.
        if command:
            inner = shlex.quote(f"cd {q_path} && {command}")
            shell_cmd = f"$SHELL -lic {inner}"
        else:
            shell_cmd = ""

        cmd = (
            f"sudo --login -u {q_user} "
            f"tmux -S {q_sock} new-session -d -s {q_session} "
            f"-c {q_path} -f {RESTRICTED_CONFIG_PATH}"
        )
        if shell_cmd:
            cmd += f" {shlex.quote(shell_cmd)}"
        run_command(cmd)

        # Fix socket permissions (tmux creates sockets mode 0700)
        run_command(f"chmod g+rwx {q_sock}")

        # Grant tmux server-access to all socket-group members
        _grant_server_access(run_command, linux_user, sock)


def kill_task_session(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
    socket_path: str | None = None,
) -> bool:
    """Kill a task's tmux session. Returns True if the session existed."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(tmux_cmd(f"kill-session -t {session}", socket_path), check=False)
    return getattr(result, "ok", True)


def session_exists(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
    socket_path: str | None = None,
) -> bool:
    """Check if a task's tmux session is alive."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(
        tmux_cmd(f"has-session -t {session}", socket_path) + " 2>/dev/null",
        check=False,
    )
    return getattr(result, "ok", False)


def send_keys(
    workspace_name: str,
    task_name: str,
    keys: str,
    *,
    run_command: RunCommand,
    socket_path: str | None = None,
) -> None:
    """Send keys to a task's tmux session."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    run_command(tmux_cmd(f"send-keys -t {session} {keys}", socket_path), check=False)


def capture_output(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
    lines: int = DEFAULT_HISTORY_LIMIT,
    socket_path: str | None = None,
) -> str:
    """Capture the scrollback buffer from a task's tmux session."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(
        tmux_cmd(f"capture-pane -t {session} -p -S -{lines}", socket_path),
        check=False,
    )
    return getattr(result, "stdout", "") or ""
