"""tmux session management for tasks.

Each task gets a locked-down tmux session. The session name follows the
pattern <workspace>--<task>. A restricted tmux config disables all interactive
session management (no splits, no new windows, no prefix key) while keeping
a large scrollback buffer.
"""

from __future__ import annotations

import shlex
from typing import Protocol

TASK_SEPARATOR = "--"
RESTRICTED_CONFIG_PATH = "/opt/agentworks/tmux-task.conf"
DEFAULT_HISTORY_LIMIT = 50_000


class RunCommand(Protocol):
    """Callable that runs a shell command on a target (e.g. partial of ssh.run)."""

    def __call__(self, command: str, *, check: bool = True) -> object: ...


def derive_session_name(workspace_name: str, task_name: str) -> str:
    """Return the tmux session name for a task: <workspace>--<task>."""
    return f"{workspace_name}{TASK_SEPARATOR}{task_name}"


def generate_restricted_config(history_limit: int = DEFAULT_HISTORY_LIMIT) -> str:
    """Generate the locked-down tmux config for task sessions.

    Loads the user's tmux.conf first so that familiar keybindings (prefix key,
    detach, copy mode, etc.) work for direct task attach. Then disables
    window/pane/session management on top to enforce one-task-per-session.
    When inside the console, the console's prefix eclipses the task's, so the
    task-level bindings are effectively invisible.
    """
    return f"""\
# Generated by agentworks. Do not edit.
# Locked-down config for task tmux sessions.
#
# Loads user tmux.conf for familiar keybindings (prefix, detach, copy mode),
# then disables window/pane/session creation to enforce one task per session.

# Load user config first
if-shell "test -f ~/.tmux.conf" "source-file ~/.tmux.conf"

# Large scrollback buffer (override user config)
set -g history-limit {history_limit}

# Disable status bar -- the console provides this when nested;
# for direct attach, the task is the only thing on screen.
set -g status off

# Disable window/pane/session creation and management.
# The user's prefix key, detach, copy mode, and scroll bindings are preserved.
unbind c          # new-window
unbind %          # split-window -h
unbind '"'        # split-window -v
unbind &          # kill-window
unbind x          # kill-pane
unbind n          # next-window
unbind p          # previous-window
unbind w          # choose-window
unbind s          # choose-session
unbind $          # rename-session
unbind ,          # rename-window
unbind .          # move-window
unbind !          # break-pane
unbind :          # command-prompt (prevents arbitrary tmux commands)
"""


def deploy_restricted_config(
    run_command: RunCommand,
    history_limit: int = DEFAULT_HISTORY_LIMIT,
) -> None:
    """Write the restricted tmux config to the VM."""
    config = generate_restricted_config(history_limit)
    # Ensure directory exists and write config
    run_command(f"sudo mkdir -p $(dirname {RESTRICTED_CONFIG_PATH})")
    run_command(f"sudo tee {RESTRICTED_CONFIG_PATH} > /dev/null << 'TMUX_CONF'\n{config}TMUX_CONF")


def create_task_session(
    workspace_name: str,
    task_name: str,
    workspace_path: str,
    command: str,
    linux_user: str | None,
    *,
    run_command: RunCommand,
    is_admin: bool = True,
) -> None:
    """Create a locked-down tmux session for a task.

    For admin mode, the command runs directly. For agent mode, the command
    is wrapped in `su --login <user>` to get a proper login shell.
    """
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    q_path = shlex.quote(workspace_path)

    if is_admin:
        if command:
            # Run via login shell so PATH (e.g. ~/.local/bin) is available
            inner = shlex.quote(f"cd {q_path} && {command}")
            shell_cmd = f"$SHELL -lc {inner}"
        else:
            shell_cmd = ""
    else:
        assert linux_user is not None
        q_user = shlex.quote(linux_user)
        if command:
            inner_cmd = shlex.quote(f"cd {q_path} && {command}")
            shell_cmd = f"sudo su --login {q_user} -c {inner_cmd}"
        else:
            shell_cmd = f"exec sudo su --login {q_user}"

    cmd = f"tmux new-session -d -s {session} -c {q_path} -f {RESTRICTED_CONFIG_PATH}"
    if shell_cmd:
        cmd += f" {shlex.quote(shell_cmd)}"

    run_command(cmd)


def kill_task_session(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
) -> bool:
    """Kill a task's tmux session. Returns True if the session existed."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(f"tmux kill-session -t {session}", check=False)
    # RunCommand protocol returns an object; we check for .ok if available
    return getattr(result, "ok", True)


def session_exists(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
) -> bool:
    """Check if a task's tmux session is alive."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(f"tmux has-session -t {session} 2>/dev/null", check=False)
    return getattr(result, "ok", False)


def capture_output(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
    lines: int = DEFAULT_HISTORY_LIMIT,
) -> str:
    """Capture the scrollback buffer from a task's tmux session."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(
        f"tmux capture-pane -t {session} -p -S -{lines}",
        check=False,
    )
    return getattr(result, "stdout", "") or ""
