"""tmux session management for tasks.

Each task gets a locked-down tmux session. The session name follows the
pattern <workspace>--<task>. A restricted tmux config disables all interactive
session management (no splits, no new windows, no prefix key) while keeping
a large scrollback buffer.
"""

from __future__ import annotations

import shlex
from typing import Protocol

TASK_SEPARATOR = "--"
RESTRICTED_CONFIG_PATH = "/opt/agentworks/tmux-task.conf"
DEFAULT_HISTORY_LIMIT = 50_000


class RunCommand(Protocol):
    """Callable that runs a shell command on a target (e.g. partial of ssh.run)."""

    def __call__(self, command: str, *, check: bool = True) -> object: ...


def derive_session_name(workspace_name: str, task_name: str) -> str:
    """Return the tmux session name for a task: <workspace>--<task>."""
    return f"{workspace_name}{TASK_SEPARATOR}{task_name}"


def generate_restricted_config(history_limit: int = DEFAULT_HISTORY_LIMIT) -> str:
    """Generate the locked-down tmux config for task sessions."""
    return f"""\
# Generated by agentworks. Do not edit.
# Locked-down config for task tmux sessions.

# Large scrollback buffer
set -g history-limit {history_limit}

# Disable status bar
set -g status off

# Disable prefix key
set -g prefix None

# Unbind all keys
unbind-key -a

# Re-bind only detach so operator can detach when attached
bind -n C-q detach-client

# Pass through ctrl-c to the running process
bind -n C-c send-keys C-c
"""


def deploy_restricted_config(
    run_command: RunCommand,
    history_limit: int = DEFAULT_HISTORY_LIMIT,
) -> None:
    """Write the restricted tmux config to the VM."""
    config = generate_restricted_config(history_limit)
    # Ensure directory exists and write config
    run_command(f"sudo mkdir -p $(dirname {RESTRICTED_CONFIG_PATH})")
    run_command(f"sudo tee {RESTRICTED_CONFIG_PATH} > /dev/null << 'TMUX_CONF'\n{config}TMUX_CONF")


def create_task_session(
    workspace_name: str,
    task_name: str,
    workspace_path: str,
    command: str,
    linux_user: str | None,
    *,
    run_command: RunCommand,
    is_admin: bool = True,
) -> None:
    """Create a locked-down tmux session for a task.

    For admin mode, the command runs directly. For agent mode, the command
    is wrapped in `su --login <user>` to get a proper login shell.
    """
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    q_path = shlex.quote(workspace_path)

    if is_admin:
        shell_cmd = f"cd {q_path} && {command}"
    else:
        assert linux_user is not None
        q_user = shlex.quote(linux_user)
        # Use su --login to get a full login shell as the agent user.
        # The inner command is passed via -c with its own quoting layer.
        inner_cmd = shlex.quote(f"cd {q_path} && {command}")
        shell_cmd = f"su --login {q_user} -c {inner_cmd}"

    run_command(
        f"tmux new-session -d -s {session} -c {q_path} "
        f"-f {RESTRICTED_CONFIG_PATH} "
        f"{shlex.quote(shell_cmd)}"
    )


def kill_task_session(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
) -> bool:
    """Kill a task's tmux session. Returns True if the session existed."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(f"tmux kill-session -t {session}", check=False)
    # RunCommand protocol returns an object; we check for .ok if available
    return getattr(result, "ok", True)


def session_exists(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
) -> bool:
    """Check if a task's tmux session is alive."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(f"tmux has-session -t {session} 2>/dev/null", check=False)
    return getattr(result, "ok", False)


def capture_output(
    workspace_name: str,
    task_name: str,
    *,
    run_command: RunCommand,
    lines: int = DEFAULT_HISTORY_LIMIT,
) -> str:
    """Capture the scrollback buffer from a task's tmux session."""
    session = shlex.quote(derive_session_name(workspace_name, task_name))
    result = run_command(
        f"tmux capture-pane -t {session} -p -S -{lines}",
        check=False,
    )
    return getattr(result, "stdout", "") or ""
