"""Tmuxinator config generation for workspace consoles.

Agentworks owns the workspace .tmuxinator.yml file. It is regenerated from DB
state on any structural change (task create/delete/restart, agent
create/delete). Manual edits will be overwritten.

The generated config produces a workspace console: an admin-shell window plus
one window per task. Task windows attach to the task's locked-down tmux
session using the same wrapper pattern as the VM console.
"""

from __future__ import annotations

import shlex
from typing import TYPE_CHECKING

from agentworks.tasks.tmux import derive_session_name, tmux_cmd

if TYPE_CHECKING:
    from agentworks.db import TaskRow

GENERATED_HEADER = "# Generated by agentworks. Changes will be overwritten."


def console_session_name(ws_name: str) -> str:
    """Return the tmux session name for a workspace console."""
    return f"ws-{ws_name}-console"


def generate_config(
    ws_name: str,
    workspace_path: str,
    tasks: list[TaskRow] | None = None,
    socket_paths: dict[str, str | None] | None = None,
) -> str:
    """Generate a tmuxinator YAML config for a workspace.

    Produces an admin-shell window plus one window per task. Task windows
    use a wrapper that attaches to the task's locked-down tmux session.

    *socket_paths* maps ``<workspace>--<task>`` keys to socket paths for
    agent-mode tasks. Admin tasks have ``None`` values (or are absent).
    """
    lines = [
        GENERATED_HEADER,
        f"name: {console_session_name(ws_name)}",
        f"root: {workspace_path}",
        "on_project_start: tmux set remain-on-exit on",
        "windows:",
        "  - admin-shell:",
        "      panes:",
        '        - ""',
    ]

    paths = socket_paths or {}
    for task in tasks or []:
        session = derive_session_name(ws_name, task.name)
        q_session = shlex.quote(session)
        sock = paths.get(session)
        # Wrapper: unset TMUX for nesting, loop attach while session exists
        has_cmd = tmux_cmd(f"has-session -t {q_session}", sock)
        attach_cmd = tmux_cmd(f"attach -t {q_session}", sock)
        wrapper = (
            f"unset TMUX; "
            f"while {has_cmd} 2>/dev/null; do "
            f"{attach_cmd}; "
            f"sleep 0.5; "
            f"done; "
            f"echo 'Task session {q_session} has ended. Press enter to close.'; "
            f"read"
        )
        lines.extend(
            [
                f"  - {session}:",
                "      panes:",
                f"        - {wrapper}",
            ]
        )

    lines.append("")  # trailing newline
    return "\n".join(lines)
