"""Tmuxinator config generation for workspace consoles.

Agentworks owns the workspace .tmuxinator.yml file. It is regenerated from DB
state on any structural change (session create/delete/restart, agent
create/delete). Manual edits will be overwritten.

The generated config produces a workspace console: an admin-shell window plus
one window per session. Session windows attach to the session's locked-down
tmux session using the same wrapper pattern as the VM console.
"""

from __future__ import annotations

import shlex
from typing import TYPE_CHECKING

from agentworks.sessions.multi_console import ADMIN_SHELL_WINDOW
from agentworks.sessions.tmux import tmux_cmd

if TYPE_CHECKING:
    from agentworks.db import SessionRow

GENERATED_HEADER = "# Generated by agentworks. Changes will be overwritten."


def console_session_name(ws_name: str) -> str:
    """Return the tmux session name for a workspace console."""
    return f"ws-{ws_name}-console"


def generate_config(
    ws_name: str,
    workspace_path: str,
    sessions: list[SessionRow] | None = None,
    socket_paths: dict[str, str | None] | None = None,
) -> str:
    """Generate a tmuxinator YAML config for a workspace.

    Produces an admin-shell window plus one window per session. Session windows
    use a wrapper that attaches to the session's locked-down tmux session.

    *socket_paths* overrides ``session.socket_path`` when provided (used to
    supply derived paths for migrated sessions with NULL socket_path).
    """
    lines = [
        GENERATED_HEADER,
        f"name: {console_session_name(ws_name)}",
        f"root: {workspace_path}",
        "on_project_start: tmux set remain-on-exit on",
        "windows:",
        # Quoted so YAML doesn't choke on the leading '--' (sentinel form
        # chosen to be impossible for any session name; see ADMIN_SHELL_WINDOW).
        f'  - "{ADMIN_SHELL_WINDOW}":',
        "      panes:",
        '        - ""',
    ]

    paths = socket_paths or {}
    for session in sessions or []:
        q_session = shlex.quote(session.name)
        sock = paths.get(session.name, session.socket_path)
        # Wrapper: unset TMUX for nesting, loop attach while session exists
        has_cmd = tmux_cmd(f"has-session -t {q_session}", sock)
        attach_cmd = tmux_cmd(f"attach -t {q_session}", sock)
        wrapper = (
            f"unset TMUX; "
            f"while {has_cmd} 2>/dev/null; do "
            f"{attach_cmd}; "
            f"sleep 0.5; "
            f"done; "
            f"echo 'Session {q_session} has ended. Press enter to close.'; "
            f"read"
        )
        lines.extend(
            [
                f"  - \"{session.name}\":",
                "      panes:",
                f"        - {wrapper}",
            ]
        )

    lines.append("")  # trailing newline
    return "\n".join(lines)
