"""Tmuxinator config generation and live session management.

Agentworks owns the workspace .tmuxinator.yml file. It is regenerated from DB
state on any structural change (agent create/delete). Manual edits will be
overwritten.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from agentworks.db import AgentRow
    from agentworks.ssh import SSHResult

GENERATED_HEADER = "# Generated by agentworks. Changes will be overwritten."


class RunCommand(Protocol):
    """Callable that runs a shell command on a target (e.g. partial of ssh.run)."""

    def __call__(self, command: str, *, check: bool = True) -> SSHResult: ...


def generate_config(
    ws_name: str,
    workspace_path: str,
    agents: list[AgentRow] | None = None,
) -> str:
    """Generate a tmuxinator YAML config for a workspace.

    Produces a user window plus one window per agent (if any).
    """
    lines = [
        GENERATED_HEADER,
        f"name: {ws_name}",
        f"root: {workspace_path}",
        "windows:",
        "  - user:",
        "      panes:",
        '        - ""',
    ]

    for agent in agents or []:
        lines.extend(
            [
                f"  - {agent.name}:",
                f"      root: {workspace_path}",
                "      panes:",
                f"        - su - {agent.linux_user}",
            ]
        )

    lines.append("")  # trailing newline
    return "\n".join(lines)


def add_window_to_session(
    ws_name: str,
    agent_name: str,
    linux_user: str,
    workspace_path: str,
    *,
    run_command: RunCommand,
) -> None:
    """Add a window to a running tmux session (best-effort)."""
    result = run_command(f"tmux has-session -t {ws_name} 2>/dev/null", check=False)
    if not result.ok:
        return

    run_command(
        f"tmux new-window -t {ws_name} -n {agent_name} -c {workspace_path} 'su - {linux_user}'",
        check=False,
    )


def remove_window_from_session(
    ws_name: str,
    agent_name: str,
    *,
    run_command: RunCommand,
) -> None:
    """Remove a window from a running tmux session (best-effort)."""
    result = run_command(f"tmux has-session -t {ws_name} 2>/dev/null", check=False)
    if not result.ok:
        return

    run_command(
        f"tmux kill-window -t {ws_name}:{agent_name}",
        check=False,
    )
