"""nerf CLI -- build and manage nerf tools."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import TYPE_CHECKING, Annotated

if TYPE_CHECKING:
    from nerftools.manifest import NerfManifest

import typer

app = typer.Typer(
    name="nerf",
    help="Build and manage nerf tools -- defanged, scoped wrappers for agent use.",
    no_args_is_help=True,
)

_BUILTIN_MANIFESTS_DIR = Path(__file__).parent.parent / "manifests"
_NERFCTL_DIR = Path(__file__).parent / "nerfctl"

_NERFCTL_FRAMEWORKS = {
    "claude": {
        "grant": _NERFCTL_DIR / "claude" / "grant.sh",
        "deny": _NERFCTL_DIR / "claude" / "deny.sh",
        "reset": _NERFCTL_DIR / "claude" / "reset.sh",
        "list": _NERFCTL_DIR / "claude" / "list.sh",
    },
}


def _load_manifests(
    user_manifests: list[Path],
    *,
    no_default: bool,
) -> list[NerfManifest]:
    from nerftools.manifest import ManifestError, load_manifest, merge_manifests

    paths: list[Path] = []
    if not no_default and _BUILTIN_MANIFESTS_DIR.exists():
        for pkg_dir in sorted(_BUILTIN_MANIFESTS_DIR.iterdir()):
            manifest_file = pkg_dir / "manifest.yaml"
            if manifest_file.exists():
                paths.append(manifest_file)

    paths.extend(user_manifests)

    loaded = []
    for p in paths:
        try:
            loaded.append(load_manifest(p))
        except ManifestError as e:
            typer.echo(f"Error: {e}", err=True)
            raise typer.Exit(1) from None

    return merge_manifests(loaded)


@app.command()
def build(
    manifests: Annotated[list[Path] | None, typer.Argument(help="Additional manifest files")] = None,
    output: Annotated[Path, typer.Option("--outdir", help="Output directory for generated scripts")] = Path("."),
    no_default: Annotated[bool, typer.Option("--no-default", help="Skip built-in manifests")] = False,
    keep_existing: Annotated[
        bool, typer.Option("--keep-existing", help="Preserve files in outdir not generated by this run")
    ] = False,
    prefix: Annotated[str, typer.Option("--prefix", help="Prefix prepended to every tool name")] = "nerf-",
    install_nerfctl: Annotated[
        list[str] | None,
        typer.Option("--install-nerfctl", help="Install nerfctl scripts for a framework (e.g. claude)"),
    ] = None,
) -> None:
    """Generate shell scripts from nerf manifests."""
    from nerftools.builder import build_scripts

    loaded = _load_manifests(manifests or [], no_default=no_default)

    if not loaded and not install_nerfctl:
        typer.echo("No manifests to build.", err=True)
        raise typer.Exit(1)

    written = build_scripts(loaded, output, keep_existing=keep_existing, prefix=prefix)
    for path in written:
        typer.echo(f"  {path}")

    if install_nerfctl:
        for framework in install_nerfctl:
            _do_install_nerfctl(framework, output)


@app.command()
def skill(
    manifests: Annotated[list[Path] | None, typer.Argument(help="Additional manifest files")] = None,
    output: Annotated[Path, typer.Option("--outdir", help="Output directory for skill files")] = Path("."),
    no_default: Annotated[bool, typer.Option("--no-default", help="Skip built-in manifests")] = False,
    keep_existing: Annotated[
        bool, typer.Option("--keep-existing", help="Preserve skill dirs in outdir not generated by this run")
    ] = False,
    prefix: Annotated[str, typer.Option("--prefix", help="Prefix prepended to every skill group and tool name")] = "nerf-",
) -> None:
    """Generate rulesync skill files from nerf manifests."""
    from nerftools.skill import build_skills

    loaded = _load_manifests(manifests or [], no_default=no_default)

    if not loaded:
        typer.echo("No manifests to generate skills from.", err=True)
        raise typer.Exit(1)

    written = build_skills(loaded, output, keep_existing=keep_existing, prefix=prefix)
    for path in written:
        typer.echo(f"  {path}")


def _do_install_nerfctl(framework: str, output: Path) -> None:
    scripts = _NERFCTL_FRAMEWORKS.get(framework)
    if scripts is None:
        known = ", ".join(_NERFCTL_FRAMEWORKS)
        typer.echo(f"Error: unknown nerfctl framework '{framework}'. Known: {known}", err=True)
        sys.exit(1)

    output.mkdir(parents=True, exist_ok=True)
    for action, src in scripts.items():
        if not src.exists():
            typer.echo(f"Error: nerfctl script not found: {src}", err=True)
            sys.exit(1)
        dest = output / f"nerfctl-{framework}-{action}"
        dest.write_bytes(src.read_bytes())
        dest.chmod(0o755)
        typer.echo(f"  {dest}")
