"""Generate bash completion script from a CommandSpec."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentworks.completions.spec import CommandSpec

# Shell snippets that provide dynamic completions.
DYNAMIC_SNIPPETS: dict[str, str] = {
    "vms": ("$(agw vm list --names-only 2>/dev/null)"),
    "vm_hosts": ("$(agw vm-host list --names-only 2>/dev/null)"),
    "workspaces": ("$(agw workspace list --names-only 2>/dev/null)"),
    "ws_templates": (
        "$(agw resource list --kind workspace-template --names-only 2>/dev/null"
        " | awk -F/ '{print $2}')"
    ),
    "git_credentials": (
        "$(agw resource list --kind git-credential --names-only 2>/dev/null"
        " | awk -F/ '{print $2}')"
    ),
    "sessions": ("$(agw session list --names-only 2>/dev/null)"),
    "agents": ("$(agw agent list --names-only 2>/dev/null)"),
    "consoles": ("$(agw console list --names-only 2>/dev/null)"),
    "session_templates": (
        "$(agw resource list --kind session-template --names-only 2>/dev/null"
        " | awk -F/ '{print $2}')"
    ),
    "vm_templates": (
        "$(agw resource list --kind vm-template --names-only 2>/dev/null"
        " | awk -F/ '{print $2}')"
    ),
    "agent_templates": (
        "$(agw resource list --kind agent-template --names-only 2>/dev/null"
        " | awk -F/ '{print $2}')"
    ),
    "secrets": ("$(agw secret list --names-only 2>/dev/null)"),
    "resource_kinds": (
        "$(agw resource kinds --names-only 2>/dev/null)"
    ),
    "resource_refs": (
        "$(agw resource list --names-only 2>/dev/null)"
    ),
    "migrate_selectors": (
        "$(agw resource list --origin operator --names-only 2>/dev/null"
        " | awk -F/ '{print $1; print $0}' | sort -u)"
    ),
}


def generate_bash(spec: CommandSpec, version: str) -> str:
    """Generate a complete bash completion script."""
    lines: list[str] = []

    lines.append("# Auto-generated by agentworks. Do not edit.")
    lines.append(f"# agentworks-completion-version: {version}")
    lines.append("#")
    lines.append("# Recommended install:  agw completion install --shell bash")
    lines.append("# (or pipe directly:    eval \"$(agw completion show --shell bash)\")")
    lines.append("")

    lines.append("_agentworks() {")
    lines.append("    local cur prev words cword")
    lines.append("    if type _init_completion &>/dev/null; then")
    lines.append("        _init_completion || return")
    lines.append("    else")
    lines.append('        cur="${COMP_WORDS[COMP_CWORD]}"')
    lines.append('        prev="${COMP_WORDS[COMP_CWORD-1]}"')
    lines.append('        words=("${COMP_WORDS[@]}")')
    lines.append("        cword=$COMP_CWORD")
    lines.append("    fi")
    lines.append("")

    _emit_dispatch(lines, spec)

    lines.append("}")
    lines.append("")
    lines.append("complete -F _agentworks agentworks")
    lines.append("complete -F _agentworks agw")
    lines.append("")

    return "\n".join(lines)


def _emit_dispatch(lines: list[str], spec: CommandSpec) -> None:
    """Emit the main dispatch logic."""
    # Build sorted subcommand names
    sub_names = sorted(spec.subcommands.keys())
    sub_names_str = " ".join(sub_names)

    lines.append("    # Determine command context")
    lines.append('    local cmd1="${words[1]:-}"')
    lines.append('    local cmd2="${words[2]:-}"')
    lines.append("")

    # Level 1: completing the top-level command name
    lines.append("    # Top-level commands")
    lines.append("    if [[ $cword -eq 1 ]]; then")
    lines.append(f'        COMPREPLY=($(compgen -W "{sub_names_str}" -- "$cur"))')
    lines.append("        return")
    lines.append("    fi")
    lines.append("")

    # Level 2: dispatch to subcommand groups
    lines.append('    case "$cmd1" in')

    for name in sub_names:
        sub = spec.subcommands[name]
        lines.append(f"        {name})")
        if sub.subcommands:
            _emit_group_completions(lines, sub)
        else:
            _emit_leaf_completions(lines, sub, token_offset=2)
        lines.append("            ;;")

    lines.append("    esac")


def _emit_group_completions(lines: list[str], spec: CommandSpec) -> None:
    """Emit completions for a command group (has subcommands)."""
    sub_names = sorted(spec.subcommands.keys())
    sub_names_str = " ".join(sub_names)

    # If we're completing the subcommand name
    lines.append("            if [[ $cword -eq 2 ]]; then")
    lines.append(f'                COMPREPLY=($(compgen -W "{sub_names_str}" -- "$cur"))')
    lines.append("                return")
    lines.append("            fi")

    # Dispatch to leaf commands
    lines.append('            case "$cmd2" in')
    for name in sub_names:
        sub = spec.subcommands[name]
        lines.append(f"                {name})")
        _emit_leaf_completions(lines, sub, token_offset=3)
        lines.append("                    ;;")
    lines.append("            esac")


def _emit_leaf_completions(lines: list[str], spec: CommandSpec, token_offset: int) -> None:
    """Emit completions for a leaf command."""
    indent = "            " if token_offset == 2 else "                    "

    options_with_values = [p for p in spec.params if not p.is_argument and not p.is_flag]
    positional_args = [p for p in spec.params if p.is_argument]
    all_options = [p for p in spec.params if not p.is_argument]

    # Check if previous token is an option expecting a value
    if options_with_values:
        lines.append(f'{indent}case "$prev" in')
        for param in options_with_values:
            opt = param.opts[0] if param.opts else f"--{param.name}"
            lines.append(f"{indent}    {opt})")
            if param.choices:
                choices_str = " ".join(param.choices)
                lines.append(f'{indent}        COMPREPLY=($(compgen -W "{choices_str}" -- "$cur"))')
            elif param.dynamic_completer and param.dynamic_completer in DYNAMIC_SNIPPETS:
                snippet = DYNAMIC_SNIPPETS[param.dynamic_completer]
                lines.append(f'{indent}        COMPREPLY=($(compgen -W "{snippet}" -- "$cur"))')
            lines.append(f"{indent}        return")
            lines.append(f"{indent}        ;;")
        lines.append(f"{indent}esac")

    # Positional argument completions. Each positional emits its own handler;
    # variadic positionals (multiple=True) match every position from theirs
    # onward (e.g. console create's "sessions" continues completing the 2nd,
    # 3rd, ... argument).
    for i, param in enumerate(positional_args):
        pos_token = token_offset + i
        cmp_op = "-ge" if param.multiple else "-eq"
        words: str | None = None
        if param.choices:
            words = " ".join(param.choices)
        elif param.dynamic_completer and param.dynamic_completer in DYNAMIC_SNIPPETS:
            words = DYNAMIC_SNIPPETS[param.dynamic_completer]
        if words:
            lines.append(f'{indent}if [[ $cword {cmp_op} {pos_token} && "$cur" != -* ]]; then')
            lines.append(f'{indent}    COMPREPLY=($(compgen -W "{words}" -- "$cur"))')
            lines.append(f"{indent}    return")
            lines.append(f"{indent}fi")

    # Fall through to option completions
    if all_options:
        opts = []
        for param in all_options:
            opt = param.opts[0] if param.opts else f"--{param.name}"
            opts.append(opt)
        opts.append("--help")
        opts_str = " ".join(opts)
        lines.append(f'{indent}if [[ "$cur" == -* ]]; then')
        lines.append(f'{indent}    COMPREPLY=($(compgen -W "{opts_str}" -- "$cur"))')
        lines.append(f"{indent}    return")
        lines.append(f"{indent}fi")
