"""Generate bash completion script from a CommandSpec."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentworks.completions.spec import CommandSpec

# Shell snippets that provide dynamic completions.
DYNAMIC_SNIPPETS: dict[str, str] = {
    "vms": ("$(agentworks vm list 2>/dev/null | tail -n +3 | awk '{print $1}')"),
    "vm_hosts": ("$(agentworks vm-host list 2>/dev/null | tail -n +3 | awk '{print $1}')"),
    "workspaces": ("$(agentworks workspace list 2>/dev/null | tail -n +3 | awk '{print $1}')"),
    "ws_templates": (
        "$(sed -n 's/^\\[workspace_templates\\.\\([^]]*\\)\\]/\\1/p'"
        ' "$HOME/.config/agentworks/config.toml" 2>/dev/null)'
    ),
    "git_credentials": (
        "$(sed -n 's/^\\[git_credentials\\.\\([^]]*\\)\\]/\\1/p' \"$HOME/.config/agentworks/config.toml\" 2>/dev/null)"
    ),
    "catalog_entries": ("$(agentworks installer list 2>/dev/null | tail -n +3 | awk '{print $2}')"),
    "tasks": ("$(agentworks task list 2>/dev/null | tail -n +3 | awk '{print $1}')"),
    "agents": ("$(agentworks agent list 2>/dev/null | tail -n +3 | awk '{print $1}')"),
    "task_templates": (
        'default $(sed -n \'s/^\\[task_templates\\.\\([^]]*\\)\\]/\\1/p\''
        ' "$HOME/.config/agentworks/config.toml" 2>/dev/null)'
    ),
}


def generate_bash(spec: CommandSpec, version: str) -> str:
    """Generate a complete bash completion script."""
    lines: list[str] = []

    lines.append("# Auto-generated by agentworks. Do not edit.")
    lines.append(f"# agentworks-completion-version: {version}")
    lines.append("#")
    lines.append("# Install:")
    lines.append("#   mkdir -p ~/.local/share/bash-completion/completions")
    lines.append("#   agentworks completion bash > ~/.local/share/bash-completion/completions/agentworks")
    lines.append("#")
    lines.append("# Or source directly in ~/.bashrc:")
    lines.append('#   eval "$(agentworks completion bash)"')
    lines.append("")

    lines.append("_agentworks() {")
    lines.append("    local cur prev words cword")
    lines.append("    if type _init_completion &>/dev/null; then")
    lines.append("        _init_completion || return")
    lines.append("    else")
    lines.append('        cur="${COMP_WORDS[COMP_CWORD]}"')
    lines.append('        prev="${COMP_WORDS[COMP_CWORD-1]}"')
    lines.append('        words=("${COMP_WORDS[@]}")')
    lines.append("        cword=$COMP_CWORD")
    lines.append("    fi")
    lines.append("")

    _emit_dispatch(lines, spec)

    lines.append("}")
    lines.append("")
    lines.append("complete -F _agentworks agentworks")
    lines.append("")

    return "\n".join(lines)


def _emit_dispatch(lines: list[str], spec: CommandSpec) -> None:
    """Emit the main dispatch logic."""
    # Build sorted subcommand names
    sub_names = sorted(spec.subcommands.keys())
    sub_names_str = " ".join(sub_names)

    lines.append("    # Determine command context")
    lines.append('    local cmd1="${words[1]:-}"')
    lines.append('    local cmd2="${words[2]:-}"')
    lines.append("")

    # Level 1: completing the top-level command name
    lines.append("    # Top-level commands")
    lines.append("    if [[ $cword -eq 1 ]]; then")
    lines.append(f'        COMPREPLY=($(compgen -W "{sub_names_str}" -- "$cur"))')
    lines.append("        return")
    lines.append("    fi")
    lines.append("")

    # Level 2: dispatch to subcommand groups
    lines.append('    case "$cmd1" in')

    for name in sub_names:
        sub = spec.subcommands[name]
        lines.append(f"        {name})")
        if sub.subcommands:
            _emit_group_completions(lines, sub)
        else:
            _emit_leaf_completions(lines, sub, token_offset=2)
        lines.append("            ;;")

    lines.append("    esac")


def _emit_group_completions(lines: list[str], spec: CommandSpec) -> None:
    """Emit completions for a command group (has subcommands)."""
    sub_names = sorted(spec.subcommands.keys())
    sub_names_str = " ".join(sub_names)

    # If we're completing the subcommand name
    lines.append("            if [[ $cword -eq 2 ]]; then")
    lines.append(f'                COMPREPLY=($(compgen -W "{sub_names_str}" -- "$cur"))')
    lines.append("                return")
    lines.append("            fi")

    # Dispatch to leaf commands
    lines.append('            case "$cmd2" in')
    for name in sub_names:
        sub = spec.subcommands[name]
        lines.append(f"                {name})")
        _emit_leaf_completions(lines, sub, token_offset=3)
        lines.append("                    ;;")
    lines.append("            esac")


def _emit_leaf_completions(lines: list[str], spec: CommandSpec, token_offset: int) -> None:
    """Emit completions for a leaf command."""
    indent = "            " if token_offset == 2 else "                    "

    options_with_values = [p for p in spec.params if not p.is_argument and not p.is_flag]
    positional_args = [p for p in spec.params if p.is_argument]
    all_options = [p for p in spec.params if not p.is_argument]

    # Check if previous token is an option expecting a value
    if options_with_values:
        lines.append(f'{indent}case "$prev" in')
        for param in options_with_values:
            opt = param.opts[0] if param.opts else f"--{param.name}"
            lines.append(f"{indent}    {opt})")
            if param.choices:
                choices_str = " ".join(param.choices)
                lines.append(f'{indent}        COMPREPLY=($(compgen -W "{choices_str}" -- "$cur"))')
            elif param.dynamic_completer and param.dynamic_completer in DYNAMIC_SNIPPETS:
                snippet = DYNAMIC_SNIPPETS[param.dynamic_completer]
                lines.append(f'{indent}        COMPREPLY=($(compgen -W "{snippet}" -- "$cur"))')
            lines.append(f"{indent}        return")
            lines.append(f"{indent}        ;;")
        lines.append(f"{indent}esac")

    # Positional argument completions
    if positional_args:
        param = positional_args[0]
        words: str | None = None
        if param.choices:
            words = " ".join(param.choices)
        elif param.dynamic_completer and param.dynamic_completer in DYNAMIC_SNIPPETS:
            words = DYNAMIC_SNIPPETS[param.dynamic_completer]
        if words:
            lines.append(f'{indent}if [[ $cword -eq {token_offset} && "$cur" != -* ]]; then')
            lines.append(f'{indent}    COMPREPLY=($(compgen -W "{words}" -- "$cur"))')
            lines.append(f"{indent}    return")
            lines.append(f"{indent}fi")

    # Fall through to option completions
    if all_options:
        opts = []
        for param in all_options:
            opt = param.opts[0] if param.opts else f"--{param.name}"
            opts.append(opt)
        opts.append("--help")
        opts_str = " ".join(opts)
        lines.append(f'{indent}if [[ "$cur" == -* ]]; then')
        lines.append(f'{indent}    COMPREPLY=($(compgen -W "{opts_str}" -- "$cur"))')
        lines.append(f"{indent}    return")
        lines.append(f"{indent}fi")
