"""Generate PowerShell completion script from a CommandSpec."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentworks.completions.spec import CommandSpec

# PowerShell snippets that provide dynamic completions.
DYNAMIC_SNIPPETS: dict[str, str] = {
    "vms": (
        "(agentworks vm list 2>$null | Select-Object -Skip 2 |"
        " ForEach-Object { ($_ -split '\\s+')[0] } |"
        " Where-Object { $_ -like \"$wordToComplete*\" })"
    ),
    "vm_hosts": (
        "(agentworks vm-host list 2>$null | Select-Object -Skip 2 |"
        " ForEach-Object { ($_ -split '\\s+')[0] } |"
        " Where-Object { $_ -like \"$wordToComplete*\" })"
    ),
    "workspaces": (
        "(agentworks workspace list 2>$null | Select-Object -Skip 2 |"
        " ForEach-Object { ($_ -split '\\s+')[0] } |"
        " Where-Object { $_ -like \"$wordToComplete*\" })"
    ),
}


def generate_powershell(spec: CommandSpec, version: str) -> str:
    """Generate a complete PowerShell completion script."""
    lines: list[str] = []

    lines.append("# Auto-generated by agentworks. Do not edit.")
    lines.append(f"# agentworks-completion-version: {version}")
    lines.append("")
    lines.append(
        "Register-ArgumentCompleter -Native -CommandName agentworks -ScriptBlock {"
    )
    lines.append(
        "    param($wordToComplete, $commandAst, $cursorPosition)"
    )
    lines.append("")
    lines.append("    $tokens = $commandAst.ToString().Trim() -split '\\s+'")
    lines.append("    $tokenCount = $tokens.Count")
    lines.append("")
    lines.append("    # Determine command context")
    lines.append("    $cmd1 = if ($tokenCount -gt 1) { $tokens[1] } else { $null }")
    lines.append("    $cmd2 = if ($tokenCount -gt 2) { $tokens[2] } else { $null }")
    lines.append("")

    _emit_dispatch(lines, spec)

    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def _emit_dispatch(lines: list[str], spec: CommandSpec) -> None:
    """Emit the main dispatch logic."""
    # Level 1: completing the top-level command/group name
    lines.append("    # Top-level commands")
    lines.append("    if ($tokenCount -le 2) {")

    for name, sub in sorted(spec.subcommands.items()):
        escaped = sub.help.replace("'", "''")
        lines.append(
            f"        [CompletionResult]::new('{name}', '{name}',"
            f" 'ParameterValue', '{escaped}')"
        )

    lines.append(
        "        | Where-Object { $_.CompletionText -like \"$wordToComplete*\" }"
    )
    lines.append("        return")
    lines.append("    }")
    lines.append("")

    # Level 2: dispatch to subcommand groups
    lines.append("    switch ($cmd1) {")

    for name, sub in sorted(spec.subcommands.items()):
        lines.append(f"        '{name}' {{")
        if sub.subcommands:
            _emit_group_completions(lines, sub, depth=2)
        else:
            _emit_leaf_completions(lines, sub)
        lines.append("        }")

    lines.append("    }")


def _emit_group_completions(
    lines: list[str], spec: CommandSpec, depth: int
) -> None:
    """Emit completions for a command group (has subcommands)."""
    indent = "    " * 3

    # If we're completing the subcommand name
    lines.append(f"{indent}if ($tokenCount -le 3) {{")

    for name, sub in sorted(spec.subcommands.items()):
        escaped = sub.help.replace("'", "''")
        lines.append(
            f"{indent}    [CompletionResult]::new('{name}', '{name}',"
            f" 'ParameterValue', '{escaped}')"
        )

    lines.append(
        f"{indent}    | Where-Object {{"
        " $_.CompletionText -like \"$wordToComplete*\" }"
    )
    lines.append(f"{indent}    return")
    lines.append(f"{indent}}}")
    lines.append("")

    # Dispatch to leaf commands
    lines.append(f"{indent}switch ($cmd2) {{")
    for name, sub in sorted(spec.subcommands.items()):
        lines.append(f"{indent}    '{name}' {{")
        _emit_param_completions(lines, sub, token_offset=3)
        lines.append(f"{indent}    }}")
    lines.append(f"{indent}}}")


def _emit_leaf_completions(
    lines: list[str], spec: CommandSpec
) -> None:
    """Emit completions for a leaf command (no subcommands)."""
    _emit_param_completions(lines, spec, token_offset=2)


def _emit_param_completions(
    lines: list[str], spec: CommandSpec, token_offset: int
) -> None:
    """Emit parameter completions for a leaf command."""
    indent = "    " * 4

    # Check if the previous token is an option expecting a value
    options_with_values = [
        p for p in spec.params if not p.is_argument and not p.is_flag
    ]
    positional_args = [p for p in spec.params if p.is_argument]

    if options_with_values:
        lines.append(f"{indent}$prevToken = $tokens[$tokenCount - 2]")
        lines.append(f"{indent}switch ($prevToken) {{")

        for param in options_with_values:
            opt = param.opts[0] if param.opts else f"--{param.name}"
            lines.append(f"{indent}    '{opt}' {{")

            if param.choices:
                for choice in param.choices:
                    lines.append(
                        f"{indent}        [CompletionResult]::new('{choice}',"
                        f" '{choice}', 'ParameterValue', '{choice}')"
                    )
                lines.append(
                    f"{indent}        | Where-Object {{"
                    " $_.CompletionText -like \"$wordToComplete*\" }"
                )
            elif param.dynamic_completer and param.dynamic_completer in DYNAMIC_SNIPPETS:
                snippet = DYNAMIC_SNIPPETS[param.dynamic_completer]
                lines.append(f"{indent}        {snippet}")
            else:
                lines.append(f"{indent}        # free text")

            lines.append(f"{indent}        return")
            lines.append(f"{indent}    }}")

        lines.append(f"{indent}}}")
        lines.append("")

    # Positional argument completions
    if positional_args:
        param = positional_args[0]
        if param.dynamic_completer and param.dynamic_completer in DYNAMIC_SNIPPETS:
            snippet = DYNAMIC_SNIPPETS[param.dynamic_completer]
            lines.append(f"{indent}# Positional: {param.name}")
            lines.append(
                f"{indent}if ($wordToComplete -notlike '-*'"
                f" -and $tokenCount -eq {token_offset + 1}) {{"
            )
            lines.append(f"{indent}    {snippet}")
            lines.append(f"{indent}    return")
            lines.append(f"{indent}}}")
            lines.append("")

    # Fall through to option completions
    all_options = [p for p in spec.params if not p.is_argument]
    if all_options:
        lines.append(f"{indent}# Options")
        lines.append(f"{indent}if ($wordToComplete -like '-*') {{")
        for param in all_options:
            opt = param.opts[0] if param.opts else f"--{param.name}"
            escaped = param.help.replace("'", "''")
            lines.append(
                f"{indent}    [CompletionResult]::new('{opt}', '{opt}',"
                f" 'ParameterValue', '{escaped}')"
            )
        lines.append(
            f"{indent}    [CompletionResult]::new('--help', '--help',"
            " 'ParameterValue', 'Show help')"
        )
        lines.append(
            f"{indent}    | Where-Object {{"
            " $_.CompletionText -like \"$wordToComplete*\" }"
        )
        lines.append(f"{indent}}}")
