"""Generate zsh completion script from a CommandSpec."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentworks.completions.spec import CommandSpec, ParamSpec

# Shell functions that provide dynamic completions.
# Each key matches a completer identifier from DYNAMIC_COMPLETIONS.
DYNAMIC_FUNCTIONS: dict[str, str] = {
    "vms": """\
_agentworks_vms() {
    local -a vms
    vms=(${(f)"$(agentworks vm list 2>/dev/null | tail -n +3 | awk '{print $1}')"})
    _describe 'vm' vms
}""",
    "vm_hosts": """\
_agentworks_vm_hosts() {
    local -a hosts
    hosts=(${(f)"$(agentworks vm-host list 2>/dev/null | tail -n +3 | awk '{print $1}')"})
    _describe 'vm-host' hosts
}""",
    "workspaces": """\
_agentworks_workspaces() {
    local -a workspaces
    workspaces=(${(f)"$(agentworks workspace list 2>/dev/null | tail -n +3 | awk '{print $1}')"})
    _describe 'workspace' workspaces
}""",
    "ws_templates": """\
_agentworks_templates() {
    local -a templates config_file
    config_file="${HOME}/.config/agentworks/config.toml"
    [[ -f "$config_file" ]] || return
    templates=(${(f)"$(sed -n 's/^\\[workspace_templates\\.\\([^]]*\\)\\]/\\1/p' "$config_file" 2>/dev/null)"})
    _describe 'template' templates
}""",
    "git_credentials": """\
_agentworks_git_credentials() {
    local -a creds config_file
    config_file="${HOME}/.config/agentworks/config.toml"
    [[ -f "$config_file" ]] || return
    creds=(${(f)"$(sed -n 's/^\\[git_credentials\\.\\([^]]*\\)\\]/\\1/p' "$config_file" 2>/dev/null)"})
    _describe 'git-credential' creds
}""",
    "catalog_entries": """\
_agentworks_catalog_entries() {
    local -a entries
    entries=(${(f)"$(agentworks installer list 2>/dev/null | tail -n +3 | awk '{print $2}')"})
    _describe 'installer' entries
}""",
}

# Maps completer identifiers to their zsh function names.
COMPLETER_FUNC_NAMES: dict[str, str] = {
    "vms": "_agentworks_vms",
    "vm_hosts": "_agentworks_vm_hosts",
    "workspaces": "_agentworks_workspaces",
    "ws_templates": "_agentworks_templates",
    "git_credentials": "_agentworks_git_credentials",
    "catalog_entries": "_agentworks_catalog_entries",
}


def generate_zsh(spec: CommandSpec, version: str) -> str:
    """Generate a complete zsh completion script."""
    lines: list[str] = []

    lines.append("#compdef agentworks")
    lines.append("")
    lines.append("# Auto-generated by agentworks. Do not edit.")
    lines.append(f"# agentworks-completion-version: {version}")
    lines.append("#")
    lines.append("# Install (Oh My Zsh):")
    lines.append("#   mkdir -p ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/completions")
    lines.append("#   agentworks completion zsh > ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/completions/_agentworks")
    lines.append("#")
    lines.append("# Install (manual):")
    lines.append("#   mkdir -p ~/.zfunc && agentworks completion zsh > ~/.zfunc/_agentworks")
    lines.append("#   then add: fpath=(~/.zfunc $fpath) to your .zshrc before compinit")
    lines.append("")

    # Emit dynamic completer functions
    used_completers = _collect_completers(spec)
    for completer_id in sorted(used_completers):
        if completer_id in DYNAMIC_FUNCTIONS:
            lines.append(DYNAMIC_FUNCTIONS[completer_id])
            lines.append("")

    # Emit the main dispatch function
    _emit_group(lines, spec, func_name="_agentworks")
    lines.append("")
    lines.append('_agentworks "$@"')
    lines.append("")

    return "\n".join(lines)


def _collect_completers(spec: CommandSpec) -> set[str]:
    """Collect all dynamic completer identifiers used in the spec tree."""
    completers: set[str] = set()
    for param in spec.params:
        if param.dynamic_completer:
            completers.add(param.dynamic_completer)
    for sub in spec.subcommands.values():
        completers.update(_collect_completers(sub))
    return completers


def _emit_group(
    lines: list[str], spec: CommandSpec, func_name: str
) -> None:
    """Emit a zsh function for a command group."""
    lines.append(f"{func_name}() {{")
    lines.append("    local -a subcommands")
    lines.append('    _arguments -C \\')
    lines.append("        '--help[Show help]' \\")
    lines.append("        '1:command:->command' \\")
    lines.append("        '*::arg:->args'")
    lines.append("")
    lines.append("    case $state in")
    lines.append("        command)")
    lines.append("            subcommands=(")

    for name, sub in sorted(spec.subcommands.items()):
        escaped_help = sub.help.replace("'", "'\\''")
        lines.append(f"                '{name}:{escaped_help}'")

    lines.append("            )")
    lines.append("            _describe 'command' subcommands")
    lines.append("            ;;")
    lines.append("        args)")
    lines.append("            case $line[1] in")

    for name, _sub in sorted(spec.subcommands.items()):
        sub_func = f"{func_name}_{name.replace('-', '_')}"
        lines.append(f"                {name})")
        lines.append(f"                    {sub_func} \"$@\"")
        lines.append("                    ;;")

    lines.append("            esac")
    lines.append("            ;;")
    lines.append("    esac")
    lines.append("}")

    # Emit sub-functions
    for name, sub in sorted(spec.subcommands.items()):
        sub_func = f"{func_name}_{name.replace('-', '_')}"
        lines.append("")
        if sub.subcommands:
            _emit_group(lines, sub, func_name=sub_func)
        else:
            _emit_leaf(lines, sub, func_name=sub_func)


def _emit_leaf(
    lines: list[str], spec: CommandSpec, func_name: str
) -> None:
    """Emit a zsh function for a leaf command."""
    args = _build_arguments(spec.params)
    if not args:
        lines.append(f"{func_name}() {{")
        lines.append("    _arguments \\")
        lines.append("        '--help[Show help]'")
        lines.append("}")
        return

    lines.append(f"{func_name}() {{")
    lines.append("    _arguments \\")
    for i, arg in enumerate(args):
        separator = " \\" if i < len(args) else ""
        lines.append(f"        {arg}{separator}")
    lines.append("        '--help[Show help]'")
    lines.append("}")


def _build_arguments(params: list[ParamSpec]) -> list[str]:
    """Build zsh _arguments specs from params."""
    args: list[str] = []
    positional_index = 1

    for param in params:
        if param.is_argument:
            label = param.name
            if param.choices:
                choices_str = " ".join(param.choices)
                args.append(f"'{positional_index}:{label}:({choices_str})'")
            elif param.dynamic_completer and param.dynamic_completer in COMPLETER_FUNC_NAMES:
                completer = f":{COMPLETER_FUNC_NAMES[param.dynamic_completer]}"
                args.append(f"'{positional_index}:{label}{completer}'")
            else:
                args.append(f"'{positional_index}:{label}:'")
            positional_index += 1
        elif param.is_flag:
            escaped_help = param.help.replace("'", "'\\''")
            opt = param.opts[0] if param.opts else f"--{param.name}"
            args.append(f"'{opt}[{escaped_help}]'")
        else:
            escaped_help = param.help.replace("'", "'\\''")
            opt = param.opts[0] if param.opts else f"--{param.name}"
            multiple = "*" if param.multiple else ""

            if param.choices:
                choices_str = " ".join(param.choices)
                args.append(
                    f"'{multiple}{opt}[{escaped_help}]:{param.name}:({choices_str})'"
                )
            elif param.dynamic_completer and param.dynamic_completer in COMPLETER_FUNC_NAMES:
                func = COMPLETER_FUNC_NAMES[param.dynamic_completer]
                args.append(
                    f"'{multiple}{opt}[{escaped_help}]:{param.name}:{func}'"
                )
            else:
                args.append(f"'{multiple}{opt}[{escaped_help}]:{param.name}:'")

    return args
