"""Generate zsh completion script from a CommandSpec."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentworks.completions.spec import CommandSpec, ParamSpec

# Shell functions that provide dynamic completions.
# Each key matches a completer identifier from DYNAMIC_COMPLETIONS.
DYNAMIC_FUNCTIONS: dict[str, str] = {
    "vms": """\
_agentworks_vms() {
    local -a vms
    vms=(${(f)"$(agw vm list --names-only 2>/dev/null)"})
    _describe 'vm' vms
}""",
    "sites": """\
_agentworks_sites() {
    local -a sites
    sites=(${(f)"$(agw resource list --kind vm-site --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'vm-site' sites
}""",
    "workspaces": """\
_agentworks_workspaces() {
    local -a workspaces
    workspaces=(${(f)"$(agw workspace list --names-only 2>/dev/null)"})
    _describe 'workspace' workspaces
}""",
    "ws_templates": """\
_agentworks_templates() {
    local -a templates
    templates=(${(f)"$(agw resource list --kind workspace-template --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'template' templates
}""",
    "git_credentials": """\
_agentworks_git_credentials() {
    local -a creds
    creds=(${(f)"$(agw resource list --kind git-credential --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'git-credential' creds
}""",
    "sessions": """\
_agentworks_sessions() {
    local -a sessions
    sessions=(${(f)"$(agw session list --names-only 2>/dev/null)"})
    _describe 'session' sessions
}""",
    "agents": """\
_agentworks_agents() {
    local -a agents
    agents=(${(f)"$(agw agent list --names-only 2>/dev/null)"})
    _describe 'agent' agents
}""",
    "consoles": """\
_agentworks_consoles() {
    local -a consoles
    consoles=(${(f)"$(agw console list --names-only 2>/dev/null)"})
    _describe 'console' consoles
}""",
    "session_templates": """\
_agentworks_session_templates() {
    local -a templates
    templates=(${(f)"$(agw resource list --kind session-template --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'session-template' templates
}""",
    "vm_templates": """\
_agentworks_vm_templates() {
    local -a templates
    templates=(${(f)"$(agw resource list --kind vm-template --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'vm-template' templates
}""",
    "agent_templates": """\
_agentworks_agent_templates() {
    local -a templates
    templates=(${(f)"$(agw resource list --kind agent-template --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'agent-template' templates
}""",
    "admin_templates": """\
_agentworks_admin_templates() {
    local -a templates
    templates=(${(f)"$(agw resource list --kind admin-template --names-only 2>/dev/null | awk -F/ '{print $2}')"})
    _describe 'admin-template' templates
}""",
    "secrets": """\
_agentworks_secrets() {
    local -a secrets
    secrets=(${(f)"$(agw secret list --names-only 2>/dev/null)"})
    _describe 'secret' secrets
}""",
    "resource_kinds": """\
_agentworks_resource_kinds() {
    local -a kinds
    kinds=(${(f)"$(agw resource kinds --names-only 2>/dev/null)"})
    _describe 'kind' kinds
}""",
    "resource_refs": """\
_agentworks_resource_refs() {
    local -a refs
    refs=(${(f)"$(agw resource list --names-only 2>/dev/null)"})
    _describe 'resource' refs
}""",
    "migrate_selectors": """\
_agentworks_migrate_selectors() {
    local -a selectors
    selectors=(${(f)"$(agw resource list --origin operator --names-only 2>/dev/null |
        awk -F/ '{print $1; print $0}' | sort -u)"})
    _describe 'selector' selectors
}""",
}

# Maps completer identifiers to their zsh function names.
COMPLETER_FUNC_NAMES: dict[str, str] = {
    "vms": "_agentworks_vms",
    "sites": "_agentworks_sites",
    "workspaces": "_agentworks_workspaces",
    "ws_templates": "_agentworks_templates",
    "git_credentials": "_agentworks_git_credentials",
    "sessions": "_agentworks_sessions",
    "session_templates": "_agentworks_session_templates",
    "vm_templates": "_agentworks_vm_templates",
    "agent_templates": "_agentworks_agent_templates",
    "admin_templates": "_agentworks_admin_templates",
    "agents": "_agentworks_agents",
    "consoles": "_agentworks_consoles",
    "secrets": "_agentworks_secrets",
    "resource_kinds": "_agentworks_resource_kinds",
    "resource_refs": "_agentworks_resource_refs",
    "migrate_selectors": "_agentworks_migrate_selectors",
}


def generate_zsh(spec: CommandSpec, version: str) -> str:
    """Generate a complete zsh completion script."""
    lines: list[str] = []

    lines.append("#compdef agentworks agw")
    lines.append("")
    lines.append("# Auto-generated by agentworks. Do not edit.")
    lines.append(f"# agentworks-completion-version: {version}")
    lines.append("#")
    lines.append("# Recommended install:  agw completion install --shell zsh")
    lines.append("# (handles Oh My Zsh and ~/.zfunc layouts and tells you when an fpath line is needed)")
    lines.append("")

    # Emit dynamic completer functions
    used_completers = _collect_completers(spec)
    for completer_id in sorted(used_completers):
        if completer_id in DYNAMIC_FUNCTIONS:
            lines.append(DYNAMIC_FUNCTIONS[completer_id])
            lines.append("")

    # Emit the main dispatch function
    _emit_group(lines, spec, func_name="_agentworks")
    lines.append("")
    lines.append('_agentworks "$@"')
    lines.append("")

    return "\n".join(lines)


def _collect_completers(spec: CommandSpec) -> set[str]:
    """Collect all dynamic completer identifiers used in the spec tree."""
    completers: set[str] = set()
    for param in spec.params:
        if param.dynamic_completer:
            completers.add(param.dynamic_completer)
    for sub in spec.subcommands.values():
        completers.update(_collect_completers(sub))
    return completers


def _emit_group(lines: list[str], spec: CommandSpec, func_name: str) -> None:
    """Emit a zsh function for a command group."""
    lines.append(f"{func_name}() {{")
    lines.append("    local -a subcommands")
    lines.append("    _arguments -C \\")
    lines.append("        '--help[Show help]' \\")
    lines.append("        '1:command:->command' \\")
    lines.append("        '*::arg:->args'")
    lines.append("")
    lines.append("    case $state in")
    lines.append("        command)")
    lines.append("            subcommands=(")

    for name, sub in sorted(spec.subcommands.items()):
        escaped_help = sub.help.replace("'", "'\\''")
        lines.append(f"                '{name}:{escaped_help}'")

    lines.append("            )")
    lines.append("            _describe 'command' subcommands")
    lines.append("            ;;")
    lines.append("        args)")
    lines.append("            case $line[1] in")

    for name, _sub in sorted(spec.subcommands.items()):
        sub_func = f"{func_name}_{name.replace('-', '_')}"
        lines.append(f"                {name})")
        lines.append(f'                    {sub_func} "$@"')
        lines.append("                    ;;")

    lines.append("            esac")
    lines.append("            ;;")
    lines.append("    esac")
    lines.append("}")

    # Emit sub-functions
    for name, sub in sorted(spec.subcommands.items()):
        sub_func = f"{func_name}_{name.replace('-', '_')}"
        lines.append("")
        if sub.subcommands:
            _emit_group(lines, sub, func_name=sub_func)
        else:
            _emit_leaf(lines, sub, func_name=sub_func)


def _emit_leaf(lines: list[str], spec: CommandSpec, func_name: str) -> None:
    """Emit a zsh function for a leaf command."""
    args = _build_arguments(spec.params)
    if not args:
        lines.append(f"{func_name}() {{")
        lines.append("    _arguments \\")
        lines.append("        '--help[Show help]'")
        lines.append("}")
        return

    lines.append(f"{func_name}() {{")
    lines.append("    _arguments \\")
    for i, arg in enumerate(args):
        separator = " \\" if i < len(args) else ""
        lines.append(f"        {arg}{separator}")
    lines.append("        '--help[Show help]'")
    lines.append("}")


def _build_arguments(params: list[ParamSpec]) -> list[str]:
    """Build zsh _arguments specs from params."""
    args: list[str] = []
    positional_index = 1

    for param in params:
        if param.is_argument:
            label = param.name
            # `*` is zsh's catchall positional spec -- matches every remaining
            # arg, which is what we want for variadic list arguments.
            position_spec = "*" if param.multiple else str(positional_index)
            if param.choices:
                choices_str = " ".join(param.choices)
                args.append(f"'{position_spec}:{label}:({choices_str})'")
            elif param.dynamic_completer and param.dynamic_completer in COMPLETER_FUNC_NAMES:
                completer = f":{COMPLETER_FUNC_NAMES[param.dynamic_completer]}"
                args.append(f"'{position_spec}:{label}{completer}'")
            else:
                args.append(f"'{position_spec}:{label}:'")
            if not param.multiple:
                positional_index += 1
        elif param.is_flag:
            escaped_help = param.help.replace("'", "'\\''")
            opt = param.opts[0] if param.opts else f"--{param.name}"
            args.append(f"'{opt}[{escaped_help}]'")
        else:
            escaped_help = param.help.replace("'", "'\\''")
            opt = param.opts[0] if param.opts else f"--{param.name}"
            multiple = "*" if param.multiple else ""

            if param.choices:
                choices_str = " ".join(param.choices)
                args.append(f"'{multiple}{opt}[{escaped_help}]:{param.name}:({choices_str})'")
            elif param.dynamic_completer and param.dynamic_completer in COMPLETER_FUNC_NAMES:
                func = COMPLETER_FUNC_NAMES[param.dynamic_completer]
                args.append(f"'{multiple}{opt}[{escaped_help}]:{param.name}:{func}'")
            else:
                args.append(f"'{multiple}{opt}[{escaped_help}]:{param.name}:'")

    return args
