#!/usr/bin/env bash

# Robust error handling
set -euo pipefail

# ============================================================================
# Workspace initialization script
#
# Sets up a freshly cloned Agentworks repository:
#   1. Configures rulesync for the developer's AI coding tools
#   2. Optionally generates a tmuxinator layout
#
# Supports both interactive and non-interactive (CLI flags) usage.
# Non-destructive; can be re-run as needed to update rulesync targets.
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Rulesync target definitions ---
# This isn't the full list, just a curated subset.
# Full list: https://rulesync.dyoshikawa.com/reference/supported-tools.html
# Adding tools beyond what the installed rulesync supports may require bumping
# the version in .rulesync-version. Please do so carefully.
# Format: "key|label"
RULESYNC_TARGETS=(
    "claudecode|Claude Code"
    "codexcli|Codex CLI"
    "geminicli|Gemini CLI"
    "copilot|GitHub Copilot"
    "gooseai|Goose AI"
    "cursor|Cursor"
    "opencode|OpenCode"
    "cline|Cline"
    "roo|Roo Code"
    "antigravity|Google Antigravity"
    "windsurf|Windsurf"
    "replit|Replit"
    "zed|Zed"
    "agentsmd|Simply generate AGENTS.md for compatible tools"
)

# ============================================================================
# Usage
# ============================================================================

usage() {
    cat <<EOF
Initialize the Agentworks workspace for development.
Non-destructive; can be re-run as needed to update rulesync targets.

Usage: $0 [OPTIONS]

Options:
    --rulesync-targets <csv>   Comma-separated rulesync targets (e.g. "claudecode,cursor")
    --help                     Print this help message

When run without flags, interactive prompts guide target selection.

Examples:
    $0
    $0 --rulesync-targets "claudecode,cursor"
EOF
    exit 0
}

# ============================================================================
# Numbered-list multi-select prompt
#
# Usage: prompt_select <result_var> <items...>
#   Each item: "key|label"
#
# Displays a numbered list and prompts for space-separated numbers.
# Sets the named variable to a comma-separated list of selected keys.
# ============================================================================

prompt_select() {
    local result_var="$1"
    shift
    local items=("$@")
    local count=${#items[@]}

    if [[ $count -eq 0 ]]; then
        printf -v "$result_var" '%s' ""
        return 0
    fi

    local keys=()
    local i
    for i in "${!items[@]}"; do
        local item="${items[$i]}"
        local key="${item%%|*}"
        local label="${item#*|}"
        keys+=("$key")
        printf "  %d) %s\n" "$((i + 1))" "$label"
    done

    echo ""
    printf "Enter numbers separated by spaces (e.g. \"1 3 5\"), or blank to skip: "
    local input
    read -r input

    local result_list=""
    for num in $input; do
        if [[ "$num" =~ ^[0-9]+$ ]] && [[ $num -ge 1 ]] && [[ $num -le $count ]]; then
            local idx=$((num - 1))
            [[ -n "$result_list" ]] && result_list+=","
            result_list+="${keys[$idx]}"
        else
            echo "Warning: Ignoring invalid selection '$num'." >&2
        fi
    done

    printf -v "$result_var" '%s' "$result_list"
}

# ============================================================================
# Step 1: Rulesync
# ============================================================================

write_rulesync_config() {
    local file="$1"
    local targets="$2"

    # Convert "a,b,c" to JSON array: "a", "b", "c"
    local json_array
    json_array=$(echo "$targets" | tr ',' '\n' | sed 's/.*/"&"/' | paste -sd ',' -)

    cat > "$file" << JSONEOF
{
  // Personal rulesync target configuration (gitignored).
  // Generated by workspace-initialize.sh.
  // To regenerate after editing this file or .rulesync/ sources:
  //   ./scripts/rulesync-upgen.sh
  // Full target list: https://rulesync.dyoshikawa.com/reference/supported-tools.html
  "targets": [${json_array}]
}
JSONEOF
}

step_setup_rulesync() {
    echo ""
    echo "--- Step 1: Rulesync ---"

    local config_file="$REPO_ROOT/rulesync.local.jsonc"

    if [[ -f "$config_file" ]]; then
        echo "rulesync.local.jsonc already exists. Skipping target selection."
        echo "Remove it first if you want to re-select targets."
    else
        local targets=""

        if [[ -n "$rulesync_targets_arg" ]]; then
            targets="$rulesync_targets_arg"
            echo "Using provided targets: $targets"
        elif [[ -t 0 ]]; then
            echo "Select the AI coding tools you use:"
            echo ""
            echo "  Different tools support different features. For details, see:"
            echo "  https://rulesync.dyoshikawa.com/reference/supported-tools.html"
            echo ""
            prompt_select targets "${RULESYNC_TARGETS[@]}"
        else
            echo "Warning: No --rulesync-targets provided and stdin is not a terminal. Skipping rulesync setup."
            return 0
        fi

        if [[ -z "$targets" ]]; then
            echo "No targets selected. Skipping rulesync configuration."
            return 0
        fi

        write_rulesync_config "$config_file" "$targets"
        echo "Wrote rulesync.local.jsonc with targets: $targets"
    fi

    # Run rulesync install/generate
    "$SCRIPT_DIR/rulesync-upgen.sh"
}

# ============================================================================
# Step 2: Tmuxinator
# ============================================================================

step_setup_tmuxinator() {
    echo ""
    echo "--- Step 2: Tmuxinator ---"

    if ! command -v tmuxinator &>/dev/null; then
        echo "tmuxinator is not installed. Skipping."
        echo "See: https://github.com/tmuxinator/tmuxinator"
        return 0
    fi

    if [[ -f "$REPO_ROOT/.tmuxinator.yml" || -f "$REPO_ROOT/.tmuxinator.yaml" ]]; then
        echo ".tmuxinator config already exists. Skipping."
        return 0
    fi

    if [[ ! -t 0 ]]; then
        echo "Skipping tmuxinator setup (non-interactive)."
        return 0
    fi

    printf "Create a .tmuxinator.yml for this workspace? (y/N): "
    local answer
    read -r answer
    if [[ ! "$answer" =~ ^[Yy] ]]; then
        echo "Skipping tmuxinator setup."
        return 0
    fi

    # Generate a random 5-char default name. Read a fixed chunk to avoid
    # SIGPIPE with pipefail.
    local random_str default_name
    random_str=$(head -c 250 /dev/urandom | LC_ALL=C tr -dc 'a-z0-9')
    default_name="${random_str:0:5}"

    echo ""
    echo "Each workspace needs a unique session name to prevent tmux from"
    echo "resuming a session in the wrong workspace."
    printf "Session name [%s]: " "$default_name"
    local session_name
    read -r session_name
    if [[ -z "$session_name" ]]; then
        session_name="$default_name"
    fi

    cat > "$REPO_ROOT/.tmuxinator.yml" << YAMLEOF
name: $session_name
root: ./

windows:
  - main:
YAMLEOF

    echo "Created a basic .tmuxinator.yml with session name: $session_name"
    echo "Start with: tmuxinator start"
}

# ============================================================================
# Main
# ============================================================================

rulesync_targets_arg=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --rulesync-targets)
            rulesync_targets_arg="$2"
            shift 2
            ;;
        --help)
            usage
            ;;
        *)
            echo "Error: Unknown argument: $1" >&2
            usage
            ;;
    esac
done

# Validate we're being run from the correct location
if [[ ! -d "$REPO_ROOT/.rulesync" ]]; then
    echo "Error: Cannot locate .rulesync/. Ensure this script is inside the Agentworks repository." >&2
    exit 1
fi

echo "=== Workspace Initialization ==="

step_setup_rulesync
step_setup_tmuxinator

echo ""
echo "=== Setup Complete ==="
